Jun 07 14:54:06 cloud-init[2406]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init-local' at Thu, 07 Jun 2018 14:54:06 +0000. Up 6.68 seconds.
Jun 07 14:54:06 cloud-init[2406]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Jun 07 14:54:06 cloud-init[2406]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
Jun 07 14:54:06 cloud-init[2406]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Jun 07 14:54:06 cloud-init[2406]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
Jun 07 14:54:06 cloud-init[2406]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Jun 07 14:54:06 cloud-init[2406]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Jun 07 14:54:06 cloud-init[2406]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
Jun 07 14:54:06 cloud-init[2406]: __init__.py[DEBUG]: Searching for data source in: []
Jun 07 14:54:06 cloud-init[2406]: cloud-init[DEBUG]: No local datasource found
Jun 07 14:54:06 cloud-init[2406]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Jun 07 14:54:06 cloud-init[2406]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Jun 07 14:54:06 cloud-init[2406]: util.py[DEBUG]: cloud-init mode 'init' took 0.051 seconds (0.05)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init' at Thu, 07 Jun 2018 14:54:06 +0000. Up 6.88 seconds.
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Running command ['ifconfig', '-a'] with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Running command ['netstat', '-rn'] with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:06 cloud-init[2413]: cloud-init[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /var/lib/cloud/data/no-net (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: cloud-init[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Searching for data source in: ['DataSourceEc2', 'DataSourceNone']
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/ec2/meta-data (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/latest/meta-data/instance-id' with {'url': 'http://169.254.169.254/latest/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 50.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-id (200, 19b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/user-data' with {'url': 'http://169.254.169.254/latest/user-data', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/' with {'url': 'http://169.254.169.254/latest/meta-data/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ (200, 268b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/root', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/iam/' with {'url': 'http://169.254.169.254/latest/meta-data/iam/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/iam/ (200, 26b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/iam/info' with {'url': 'http://169.254.169.254/latest/meta-data/iam/info', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/iam/info (200, 198b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/metrics/' with {'url': 'http://169.254.169.254/latest/meta-data/metrics/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/metrics/ (200, 7b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/latest/meta-data/metrics/vhostmd', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/' with {'url': 'http://169.254.169.254/latest/meta-data/network/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/ (200, 11b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/ (200, 5b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/ (200, 230b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/ipv4-associations/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/ipv4-associations/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/ipv4-associations/ (200, 13b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/ipv4-associations/18.206.149.10' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/ipv4-associations/18.206.149.10', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/ipv4-associations/18.206.149.10 (200, 12b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/local-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/local-hostname (200, 28b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/security-groups' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/security-groups', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/security-groups (200, 8b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/public-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/public-hostname (200, 41b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/vpc-ipv4-cidr-blocks', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/subnet-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/subnet-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/subnet-id (200, 15b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/public-ipv4s' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/public-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/public-ipv4s (200, 13b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/interface-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/interface-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/interface-id (200, 12b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/mac' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/mac', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/mac (200, 17b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/security-group-ids' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/security-group-ids', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/security-group-ids (200, 11b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/vpc-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/local-ipv4s' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/local-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/local-ipv4s (200, 12b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/owner-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/owner-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/owner-id (200, 12b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/subnet-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/subnet-ipv4-cidr-block (200, 13b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/device-number' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/device-number', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/device-number (200, 1b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/vpc-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/vpc-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/02:df:5f:c1:ea:98/vpc-id (200, 12b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/' with {'url': 'http://169.254.169.254/latest/meta-data/placement/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/ (200, 17b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/latest/meta-data/placement/availability-zone', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/availability-zone (200, 10b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-keys/' with {'url': 'http://169.254.169.254/latest/meta-data/public-keys/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-keys/ (200, 13b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key (200, 393b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/' with {'url': 'http://169.254.169.254/latest/meta-data/services/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/ (200, 16b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/domain' with {'url': 'http://169.254.169.254/latest/meta-data/services/domain', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/domain (200, 13b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/partition' with {'url': 'http://169.254.169.254/latest/meta-data/services/partition', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/partition (200, 3b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/profile' with {'url': 'http://169.254.169.254/latest/meta-data/profile', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/profile (200, 11b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/local-ipv4', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-ipv4 (200, 12b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/reservation-id' with {'url': 'http://169.254.169.254/latest/meta-data/reservation-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/reservation-id (200, 19b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-hostname (200, 28b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/security-groups' with {'url': 'http://169.254.169.254/latest/meta-data/security-groups', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/security-groups (200, 8b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/latest/meta-data/ami-launch-index', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-launch-index (200, 1b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-hostname (200, 41b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/hostname' with {'url': 'http://169.254.169.254/latest/meta-data/hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/hostname (200, 28b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-id' with {'url': 'http://169.254.169.254/latest/meta-data/ami-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-id (200, 12b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-action' with {'url': 'http://169.254.169.254/latest/meta-data/instance-action', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-action (200, 4b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/mac' with {'url': 'http://169.254.169.254/latest/meta-data/mac', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/mac (200, 17b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/public-ipv4', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-ipv4 (200, 13b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/latest/meta-data/ami-manifest-path', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-manifest-path (200, 9b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-type' with {'url': 'http://169.254.169.254/latest/meta-data/instance-type', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-type (200, 8b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-id' with {'url': 'http://169.254.169.254/latest/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-id (200, 19b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity (200, 33b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/document', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/document (200, 467b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/rsa2048', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/rsa2048 (200, 1422b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/pkcs7', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 (200, 1102b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/signature', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Jun 07 14:54:06 cloud-init[2413]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/signature (200, 174b) after 1 attempts
Jun 07 14:54:06 cloud-init[2413]: DataSourceEc2.py[DEBUG]: Crawl of metadata service took 0 seconds
Jun 07 14:54:06 cloud-init[2413]: stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 82 bytes from /proc/cmdline
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0fcf7d9a887243b84'
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0fcf7d9a887243b84/datasource (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/datasource - wb: [644] 29 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: cloud-init[DEBUG]: init will now be targeting instance id: i-0fcf7d9a887243b84
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 82 bytes from /proc/cmdline
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8571 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/user-data.txt - wb: [600] 0 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/user-data.txt.i - wb: [600] 345 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/vendor-data.txt - wb: [600] 4 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/vendor-data.txt.i - wb: [600] 345 bytes
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/consume_data - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/consume_data'>)
Jun 07 14:54:06 cloud-init[2413]: launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: {'Content-Type': 'text/x-not-multipart', 'Content-Disposition': 'attachment; filename="part-001"', 'MIME-Version': '1.0'}
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Empty payload of type text/x-not-multipart
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/cloud-config.txt - wb: [600] 0 bytes
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: no vendordata from datasource
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 82 bytes from /proc/cmdline
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: load_yaml given empty string, returning default
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: load_yaml given empty string, returning default
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Jun 07 14:54:06 cloud-init[2413]: stages.py[INFO]: Skipping modules ['resolv-conf'] because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7fdd0b466bd0>)
Jun 07 14:54:06 cloud-init[2413]: cc_migrator.py[DEBUG]: Migrating semaphores which are not named canonically.
Jun 07 14:54:06 cloud-init[2413]: cc_migrator.py[DEBUG]: Looking at consume_data
Jun 07 14:54:06 cloud-init[2413]: cc_migrator.py[DEBUG]: Searching for legacy per-instance semaphores under /var/lib/cloud/sem
Jun 07 14:54:06 cloud-init[2413]: cc_migrator.py[DEBUG]: Migrating semaphores which have been renamed or split.
Jun 07 14:54:06 cloud-init[2413]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem
Jun 07 14:54:06 cloud-init[2413]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/sem
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_rsyslog - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_rsyslog'>)
Jun 07 14:54:06 cloud-init[2413]: cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7fdd0bf62c90>)
Jun 07 14:54:06 cloud-init[2413]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_write_files - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_write_files'>)
Jun 07 14:54:06 cloud-init[2413]: cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_metadata.pyc'>) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_write_metadata - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_write_metadata'>)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /etc/yum/vars/awsregion - wb: [644] 9 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsregion to 0:0
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /etc/yum/vars/awsdomain - wb: [644] 13 bytes
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsdomain to 0:0
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fdd0bc49ed0>)
Jun 07 14:54:06 cloud-init[2413]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /proc/2413/mountinfo (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 528 bytes from /proc/2413/mountinfo
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /sys/devices/vbd-51712/block/xvda/dev (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-51712/block/xvda/dev
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: resize_devices took 0.032 seconds
Jun 07 14:54:06 cloud-init[2413]: cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/xvda, 1)
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7fdd0bc42ed0>)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /proc/2413/mountinfo (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 528 bytes from /proc/2413/mountinfo
Jun 07 14:54:06 cloud-init[2413]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 53 bytes from /proc/1/environ
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 1251 bytes from /proc/self/status
Jun 07 14:54:06 cloud-init[2413]: cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/xvda1
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Forked child 2456 who will run callback log_time
Jun 07 14:54:06 cloud-init[2413]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=ext4, val=noblock)
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_set_hostname - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-set-hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_set_hostname'>)
Jun 07 14:54:06 cloud-init[2413]: cc_set_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not setting the hostname in module set-hostname
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fdd0b3d7a90>)
Jun 07 14:54:06 cloud-init[2413]: cc_update_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not updating the hostname in module update-hostname
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7fdd0b3d79d0>)
Jun 07 14:54:06 cloud-init[2413]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module resolv-conf (<module 'cloudinit.config.cc_resolv_conf' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resolv_conf.pyc'>) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_resolv_conf - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-resolv-conf using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_resolv_conf'>)
Jun 07 14:54:06 cloud-init[2413]: cc_resolv_conf.py[DEBUG]: Skipping module named resolv-conf, no 'manage_resolv_conf' key in configuration
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_users_groups - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_users_groups'>)
Jun 07 14:54:06 cloud-init[2413]: __init__.py[DEBUG]: Adding user ec2-user
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ec2-user', '--shell', '/bin/bash', '--comment', 'EC2 Default User', '--groups', 'wheel', '-m']
Jun 07 14:54:06 cloud-init[2456]: util.py[DEBUG]: Running command ('resize2fs', '/dev/xvda1') with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:06 cloud-init[2456]: util.py[DEBUG]: backgrounded Resizing took 0.006 seconds
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Running command ['usermod', '-L', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Read 3729 bytes from /etc/sudoers
Jun 07 14:54:06 cloud-init[2413]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_ssh - wb: [644] 20 bytes
Jun 07 14:54:06 cloud-init[2413]: helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_ssh'>)
Jun 07 14:54:06 cloud-init[2413]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=False)
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=False)
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=False)
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 500:500
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 393 bytes
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 500:500
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 550 bytes
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
Jun 07 14:54:07 cloud-init[2413]: cloud-init[DEBUG]: Ran 13 modules with 0 failures
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Jun 07 14:54:07 cloud-init[2413]: util.py[DEBUG]: cloud-init mode 'init' took 0.628 seconds (0.62)
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:config' at Thu, 07 Jun 2018 14:54:07 +0000. Up 7.64 seconds.
Jun 07 14:54:07 cloud-init[2480]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Jun 07 14:54:07 cloud-init[2480]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_mounts - wb: [644] 19 bytes
Jun 07 14:54:07 cloud-init[2480]: helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_mounts'>)
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Jun 07 14:54:07 cloud-init[2480]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount ephemeral0
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: changed ephemeral0 => None
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Jun 07 14:54:07 cloud-init[2480]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount swap
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: changed swap => None
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Jun 07 14:54:07 cloud-init[2480]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount ephemeral0
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Jun 07 14:54:07 cloud-init[2480]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount swap
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: no need to setup swap
Jun 07 14:54:07 cloud-init[2480]: cc_mounts.py[DEBUG]: No modifications to fstab needed.
Jun 07 14:54:07 cloud-init[2480]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_locale - wb: [644] 20 bytes
Jun 07 14:54:07 cloud-init[2480]: helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_locale'>)
Jun 07 14:54:07 cloud-init[2480]: cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Reading from /etc/sysconfig/i18n (quiet=False)
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Read 19 bytes from /etc/sysconfig/i18n
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Writing to /etc/sysconfig/i18n - wb: [644] 17 bytes
Jun 07 14:54:07 cloud-init[2480]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_set_passwords - wb: [644] 20 bytes
Jun 07 14:54:07 cloud-init[2480]: helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_set_passwords'>)
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Jun 07 14:54:07 cloud-init[2480]: cc_set_passwords.py[DEBUG]: Replacing auth line 65 with no
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Writing to /etc/ssh/sshd_config - wb: [644] 3934 bytes
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Running command ['service', 'sshd', 'status'] with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:07 cloud-init[2480]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_yum_configure - wb: [644] 20 bytes
Jun 07 14:54:07 cloud-init[2480]: helpers.py[DEBUG]: Running config-yum-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_yum_configure'>)
Jun 07 14:54:07 cloud-init[2480]: cc_yum_configure.py[DEBUG]: Generating default repo files
Jun 07 14:54:07 cloud-init[2480]: __init__.py[DEBUG]: filtered distro mirror info: {'regional': u'repo.us-east-1.amazonaws.com'}
Jun 07 14:54:07 cloud-init[2480]: cc_yum_configure.py[DEBUG]: Using mirror: repo.us-east-1.amazonaws.com
Jun 07 14:54:07 cloud-init[2480]: cc_yum_configure.py[INFO]: No releasever provided, leaving yum.conf unchanged.
Jun 07 14:54:07 cloud-init[2480]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_yum_add_repo - wb: [644] 20 bytes
Jun 07 14:54:07 cloud-init[2480]: helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_yum_add_repo'>)
Jun 07 14:54:07 cloud-init[2480]: cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
Jun 07 14:54:07 cloud-init[2480]: stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) with frequency once-per-instance
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_package_update_upgrade_install - wb: [644] 20 bytes
Jun 07 14:54:07 cloud-init[2480]: helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_package_update_upgrade_install'>)
Jun 07 14:54:07 cloud-init[2480]: amazon.py[DEBUG]: Upgrade level: security
Jun 07 14:54:07 cloud-init[2480]: util.py[DEBUG]: Running command ['yum', '-t', '-y', '--exclude=kernel', '--exclude=nvidia*', '--exclude=cudatoolkit', '--security', '--sec-severity=critical', '--sec-severity=important', 'upgrade'] with allowed return codes [0] (shell=False, capture=False)
Jun 07 14:54:39 cloud-init[2480]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
Jun 07 14:54:39 cloud-init[2480]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_timezone - wb: [644] 20 bytes
Jun 07 14:54:39 cloud-init[2480]: helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_timezone'>)
Jun 07 14:54:39 cloud-init[2480]: cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
Jun 07 14:54:39 cloud-init[2480]: stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_puppet.pyc'>) with frequency once-per-instance
Jun 07 14:54:39 cloud-init[2480]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_puppet - wb: [644] 20 bytes
Jun 07 14:54:39 cloud-init[2480]: helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_puppet'>)
Jun 07 14:54:39 cloud-init[2480]: cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
Jun 07 14:54:39 cloud-init[2480]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
Jun 07 14:54:39 cloud-init[2480]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fa818248690>)
Jun 07 14:54:39 cloud-init[2480]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
Jun 07 14:54:39 cloud-init[2480]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
Jun 07 14:54:39 cloud-init[2480]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_runcmd - wb: [644] 20 bytes
Jun 07 14:54:39 cloud-init[2480]: helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_runcmd'>)
Jun 07 14:54:39 cloud-init[2480]: cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
Jun 07 14:54:39 cloud-init[2480]: cloud-init[DEBUG]: Ran 10 modules with 0 failures
Jun 07 14:54:39 cloud-init[2480]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Jun 07 14:54:39 cloud-init[2480]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
Jun 07 14:54:39 cloud-init[2480]: util.py[DEBUG]: cloud-init mode 'modules' took 31.799 seconds (31.80)
Jun 07 14:54:39 cloud-init[2664]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:final' at Thu, 07 Jun 2018 14:54:39 +0000. Up 40.15 seconds.
Jun 07 14:54:39 cloud-init[2664]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Jun 07 14:54:39 cloud-init[2664]: stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_per_once.pyc'>) with frequency once
Jun 07 14:54:39 cloud-init[2664]: util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 20 bytes
Jun 07 14:54:39 cloud-init[2664]: helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
Jun 07 14:54:39 cloud-init[2664]: stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_per_boot.pyc'>) with frequency always
Jun 07 14:54:39 cloud-init[2664]: helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7fca42e3c690>)
Jun 07 14:54:39 cloud-init[2664]: stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_per_instance.pyc'>) with frequency once-per-instance
Jun 07 14:54:39 cloud-init[2664]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_scripts_per_instance - wb: [644] 20 bytes
Jun 07 14:54:39 cloud-init[2664]: helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_scripts_per_instance'>)
Jun 07 14:54:39 cloud-init[2664]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency once-per-instance
Jun 07 14:54:39 cloud-init[2664]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_scripts_user - wb: [644] 20 bytes
Jun 07 14:54:39 cloud-init[2664]: helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_scripts_user'>)
Jun 07 14:54:39 cloud-init[2664]: stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) with frequency once-per-instance
Jun 07 14:54:39 cloud-init[2664]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_ssh_authkey_fingerprints - wb: [644] 20 bytes
Jun 07 14:54:39 cloud-init[2664]: helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_ssh_authkey_fingerprints'>)
Jun 07 14:54:39 cloud-init[2664]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Jun 07 14:54:39 cloud-init[2664]: util.py[DEBUG]: Read 3934 bytes from /etc/ssh/sshd_config
Jun 07 14:54:39 cloud-init[2664]: util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
Jun 07 14:54:39 cloud-init[2664]: util.py[DEBUG]: Read 393 bytes from /home/ec2-user/.ssh/authorized_keys
Jun 07 14:54:40 cloud-init[2664]: stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_keys_to_console.pyc'>) with frequency once-per-instance
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_keys_to_console - wb: [644] 20 bytes
Jun 07 14:54:40 cloud-init[2664]: helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_keys_to_console'>)
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Running command ['/usr/libexec/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
Jun 07 14:54:40 cloud-init[2664]: stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_phone_home.pyc'>) with frequency once-per-instance
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_phone_home - wb: [644] 20 bytes
Jun 07 14:54:40 cloud-init[2664]: helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_phone_home'>)
Jun 07 14:54:40 cloud-init[2664]: cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
Jun 07 14:54:40 cloud-init[2664]: stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_final_message.pyc'>) with frequency always
Jun 07 14:54:40 cloud-init[2664]: helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7fca42b03110>)
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Cloud-init v. 0.7.6 finished at Thu, 07 Jun 2018 14:54:40 +0000. Datasource DataSourceEc2.  Up 40.47 seconds
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 51 bytes
Jun 07 14:54:40 cloud-init[2664]: stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_power_state_change.pyc'>) with frequency once-per-instance
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_power_state_change - wb: [644] 20 bytes
Jun 07 14:54:40 cloud-init[2664]: helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-0fcf7d9a887243b84/sem/config_power_state_change'>)
Jun 07 14:54:40 cloud-init[2664]: cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
Jun 07 14:54:40 cloud-init[2664]: cloud-init[DEBUG]: Ran 9 modules with 0 failures
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
Jun 07 14:54:40 cloud-init[2664]: util.py[DEBUG]: cloud-init mode 'modules' took 0.329 seconds (0.33)
